# Generated by Django 4.2.4 on 2023-09-26 09:22

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=0.5, size=[400, 400], upload_to=courses.models.make_enrollment_image_file_path)),
                ('guardian_first_name', models.CharField(max_length=50)),
                ('guardian_last_name', models.CharField(max_length=50)),
                ('guardian_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('guardian_email', models.EmailField(max_length=256)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('guardian_address', models.CharField(max_length=256)),
                ('highest_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('school_attended', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.CharField(choices=[('Weekdays (Morning)', 'Weekdays (Morning)'), ('Weekdays (Afternoon)', 'Weekdays (Afternoon)'), ('Weekends', 'Weekends')], max_length=50)),
                ('learning_center', models.CharField(choices=[('farm center', 'Farm Center'), ('rijiyar zaki', 'Rijiya Zaki')], max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('scholarship', models.BooleanField(default=False)),
                ('enrolled_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_of_study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_course', to='courses.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'unique_together': {('course_of_study', 'student')},
            },
        ),
    ]
