# Generated by Django 4.2.4 on 2023-09-27 13:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=256, null=True)),
                ('guardian_full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('primary_school', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_school', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'grauduate',
                'verbose_name_plural': 'grauduates',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
