# Generated by Django 4.2.4 on 2023-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_graduate_enrollment_graduate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduate',
            options={'verbose_name': 'graduate', 'verbose_name_plural': 'graduates'},
        ),
        migrations.AlterField(
            model_name='graduate',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
