# Generated by Django 4.2.5 on 2023-09-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_graduate_guardian_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduate',
            old_name='guardian_phone_number',
            new_name='guardian_phone',
        ),
    ]
