# Generated by Django 4.2.5 on 2023-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_guardian_phone_number_graduate_guardian_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
