# Generated by Django 4.2.5 on 2023-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_graduate_gender_alter_graduate_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
