# Generated by Django 4.2.4 on 2023-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=250)),
                ('question_ha', models.CharField(max_length=250)),
                ('answer_en', models.CharField(max_length=250)),
                ('answer_ha', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'faq',
                'verbose_name_plural': 'faqs',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('testimonial', models.TextField()),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
            },
        ),
    ]
